name: ngs-class
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - notebook=5.7.5
  - jupyterlab=1.2
  - ipywidgets=7.5
  - rpy2=2.9.4
  - numpy=1.18.1
  - ipython=7.13.0
  - pandas=1.0.3

  - r-base=3.6.1
  - star=2.6.1d
  - picard=2.21.1
  - rseqc=3.0.1

  - conda-forge::r-data.table=1.12.4
  - conda-forge::r-gplots=3.0.1.1
  - conda-forge::r-markdown=1.1
  - conda-forge::r-rcolorbrewer=1.1_2

  - bioconductor-deseq2=3.11
  - bioconductor-dupradar=1.14.0
  - bioconductor-edger=3.26.5
  - bioconductor-tximeta=1.2.2
  - bioconductor-summarizedexperiment=1.14.0

  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.8
  - bioconda::trimmomatic=0.39
  - bioconda::sra-tools=2.10.3
  - bioconda::goatools=1.0.5

  - pip
  - pip: 
    - ncbi-acc-download
    - ncbi-genome-download
    - matplotlib-venn
