#!/bin/bash
conda install -c bioconda bioconductor-deseq2
conda install -c bioconda r-ggrepel
conda install -c r r-ggplot2
mkdir raw_files && cd raw_files
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/008/SRR7261718/SRR7261718_1.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/008/SRR7261718/SRR7261718_2.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/009/SRR7261719/SRR7261719_1.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/009/SRR7261719/SRR7261719_2.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/000/SRR7261720/SRR7261720_1.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/000/SRR7261720/SRR7261720_2.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/001/SRR7261721/SRR7261721_1.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/001/SRR7261721/SRR7261721_2.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/002/SRR7261722/SRR7261722_1.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/002/SRR7261722/SRR7261722_2.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/003/SRR7261723/SRR7261723_1.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/003/SRR7261723/SRR7261723_2.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/004/SRR7261724/SRR7261724_1.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/004/SRR7261724/SRR7261724_2.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/005/SRR7261725/SRR7261725_1.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/005/SRR7261725/SRR7261725_2.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/006/SRR7261726/SRR7261726_1.fastq.gz
wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR726/006/SRR7261726/SRR7261726_2.fastq.gz
mv SRR7261718_1.fastq.gz WT1_1.fastq.gz
mv SRR7261718_2.fastq.gz WT1_2.fastq.gz
mv SRR7261719_1.fastq.gz WT2_1.fastq.gz
mv SRR7261719_2.fastq.gz WT2_2.fastq.gz
mv SRR7261720_1.fastq.gz WT3_1.fastq.gz
mv SRR7261720_2.fastq.gz WT3_2.fastq.gz
mv SRR7261721_1.fastq.gz Urban1_1.fastq.gz
mv SRR7261721_2.fastq.gz Urban1_2.fastq.gz
mv SRR7261722_1.fastq.gz Urban2_1.fastq.gz
mv SRR7261722_2.fastq.gz Urban2_2.fastq.gz
mv SRR7261723_1.fastq.gz Urban3_1.fastq.gz
mv SRR7261723_2.fastq.gz Urban3_2.fastq.gz
mv SRR7261724_1.fastq.gz Diesel1_1.fastq.gz
mv SRR7261724_2.fastq.gz Diesel1_2.fastq.gz
mv SRR7261725_1.fastq.gz Diesel2_1.fastq.gz
mv SRR7261725_2.fastq.gz Diesel2_2.fastq.gz
mv SRR7261726_1.fastq.gz Diesel3_1.fastq.gz
mv SRR7261726_2.fastq.gz Diesel3_2.fastq.gz
curl -O -J -L https://osf.io/v24pt/download && cd ..
mkdir references && cd references && wget -O ecoli.fasta "ftp://ftp.ensemblgenomes.org/pub/bacteria/release-45/fasta/bacteria_0_collection/escherichia_coli_str_k_12_substr_mg1655/dna/Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.dna.toplevel.fa.gz" && wget -O ecoli_genes.gtf "ftp://ftp.ensemblgenomes.org/pub/bacteria/release-45/gtf/bacteria_0_collection/escherichia_coli_str_k_12_substr_mg1655/Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.45.gtf.gz" && cd ..