#!/bin/bash
mkdir raw_files
fastq-dump --split-files --gzip --outdir rawfiles/ SAMN09354753
fastq-dump --split-files --gzip --outdir rawfiles/ SAMN09354752
fastq-dump --split-files --gzip --outdir rawfiles/ SAMN09354751
fastq-dump --split-files --gzip --outdir rawfiles/ SAMN09354750
fastq-dump --split-files --gzip --outdir rawfiles/ SAMN09354749
fastq-dump --split-files --gzip --outdir rawfiles/ SAMN09354748
fastq-dump --split-files --gzip --outdir rawfiles/ SAMN09354747
fastq-dump --split-files --gzip --outdir rawfiles/ SAMN09354746
fastq-dump --split-files --gzip --outdir rawfiles/ SAMN09354745
cd raw_files && curl -O -J -L https://osf.io/v24pt/download && cd ..
mkdir references && cd references && ncbi-acc-download --format fasta NZ_CP009273.1 && wget -O ecoli_genes.gff "https://www.ncbi.nlm.nih.gov/sviewer/viewer.cgi?db=nuccore&report=gff3&id=NZ_CP009273.1" && cd ..